<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShopSeeder extends Seeder
{
    public function run(): void
    {
        $shops = [
            [
                'id' => 1,
                'name' => 'Sharma Medical Store',
                'owner_name' => 'Rajesh Sharma',
                'phone' => '9876543210',
                'area' => 'Mithanpura',
                'address' => 'Near Mithanpura Chowk, Muzaffarpur',
                'rating' => 4.8,
                'reviews' => 124,
                'distance_km' => 0.4,
                'is_top' => true,
                'delivery_enabled' => true,
                'is_online' => true,
                'status' => 'approved',
                'user_id' => 2,
                'latitude' => 26.12000000,
                'longitude' => 85.36400000,
            ],
            [
                'id' => 2,
                'name' => 'Gupta Pharma',
                'owner_name' => 'Anil Gupta',
                'phone' => '9123456780',
                'area' => 'Brahmpura',
                'address' => 'Brahmpura Main Road, Muzaffarpur',
                'rating' => 4.5,
                'reviews' => 89,
                'distance_km' => 1.2,
                'is_top' => false,
                'delivery_enabled' => true,
                'is_online' => true,
                'status' => 'approved',
                'user_id' => 3,
                'latitude' => 26.12500000,
                'longitude' => 85.37000000,
            ],
            [
                'id' => 3,
                'name' => 'Singh Medical',
                'owner_name' => 'Vikram Singh',
                'phone' => '9988776655',
                'area' => 'Juran Chapra',
                'address' => 'Road No. 2, Juran Chapra, Muzaffarpur',
                'rating' => 4.7,
                'reviews' => 203,
                'distance_km' => 2.1,
                'is_top' => false,
                'delivery_enabled' => true,
                'is_online' => true,
                'status' => 'approved',
                'user_id' => 4,
                'latitude' => 26.11500000,
                'longitude' => 85.35500000,
            ],
            [
                'id' => 4,
                'name' => 'Yadav Medical',
                'owner_name' => 'Suresh Yadav',
                'phone' => '9090909090',
                'area' => 'Ramna Road',
                'address' => 'Ramna Road, Near University, Muzaffarpur',
                'rating' => 4.3,
                'reviews' => 56,
                'distance_km' => 2.8,
                'is_top' => false,
                'delivery_enabled' => true,
                'is_online' => true,
                'status' => 'blocked',
                'user_id' => null,
                'latitude' => 26.13000000,
                'longitude' => 85.36000000,
            ],
            [
                'id' => 5,
                'name' => 'Verma Pharmacy',
                'owner_name' => 'Pooja Verma',
                'phone' => '9555512345',
                'area' => 'Aghoria Bazar',
                'address' => 'Aghoria Bazar Chowk, Muzaffarpur',
                'rating' => 5.0,
                'reviews' => 0,
                'distance_km' => 3.5,
                'is_top' => false,
                'delivery_enabled' => true,
                'is_online' => true,
                'status' => 'pending',
                'user_id' => null,
                'latitude' => 26.11000000,
                'longitude' => 85.38000000,
            ],
            [
                'id' => 6,
                'name' => 'Patna Junction Pharmacy',
                'owner_name' => 'Ravi Kumar',
                'phone' => '9888812345',
                'area' => 'Station Road',
                'address' => 'Station Road, Patna',
                'rating' => 4.6,
                'reviews' => 45,
                'distance_km' => 1.5,
                'is_top' => true,
                'delivery_enabled' => true,
                'is_online' => true,
                'status' => 'approved',
                'user_id' => null,
                'latitude' => 25.60220000,
                'longitude' => 85.13760000,
            ],
            [
                'id' => 7,
                'name' => 'Pataliputra Medical Hall',
                'owner_name' => 'Sanjay Mishra',
                'phone' => '9777712345',
                'area' => 'Pataliputra Colony',
                'address' => 'Pataliputra Colony, Patna',
                'rating' => 4.4,
                'reviews' => 31,
                'distance_km' => 2.9,
                'is_top' => false,
                'delivery_enabled' => true,
                'is_online' => true,
                'status' => 'approved',
                'user_id' => null,
                'latitude' => 25.62680000,
                'longitude' => 85.11180000,
            ],
            [
                'id' => 8,
                'name' => 'Pink City Medicos',
                'owner_name' => 'Mahendra Sharma',
                'phone' => '9666612345',
                'area' => 'Johri Bazar',
                'address' => 'Johri Bazar, Jaipur',
                'rating' => 4.9,
                'reviews' => 112,
                'distance_km' => 0.8,
                'is_top' => true,
                'delivery_enabled' => true,
                'is_online' => true,
                'status' => 'approved',
                'user_id' => null,
                'latitude' => 26.91960000,
                'longitude' => 75.82420000,
            ],
            [
                'id' => 9,
                'name' => 'Malviya Nagar Pharmacy',
                'owner_name' => 'Pankaj Gupta',
                'phone' => '9555567890',
                'area' => 'Malviya Nagar',
                'address' => 'Malviya Nagar, Jaipur',
                'rating' => 4.5,
                'reviews' => 64,
                'distance_km' => 3.1,
                'is_top' => false,
                'delivery_enabled' => true,
                'is_online' => true,
                'status' => 'approved',
                'user_id' => null,
                'latitude' => 26.85300000,
                'longitude' => 75.80480000,
            ],
            [
                'id' => 10,
                'name' => 'Mithila Medicals',
                'owner_name' => 'Ramanuj Jha',
                'phone' => '9444412345',
                'area' => 'Tower Chowk',
                'address' => 'Tower Chowk, Darbhanga',
                'rating' => 4.7,
                'reviews' => 98,
                'distance_km' => 1.1,
                'is_top' => true,
                'delivery_enabled' => true,
                'is_online' => true,
                'status' => 'approved',
                'user_id' => null,
                'latitude' => 26.15580000,
                'longitude' => 85.89580000,
            ]
        ];

        foreach ($shops as $shop) {
            DB::table('shops')->updateOrInsert(['id' => $shop['id']], array_merge($shop, ['created_at' => now(), 'updated_at' => now()]));
        }

        $wallets = [
            ['shop_id' => 1, 'total_sales' => 4820, 'due_commission' => 45, 'credit_limit' => 100, 'status' => 'active'],
            ['shop_id' => 2, 'total_sales' => 2100, 'due_commission' => 138, 'credit_limit' => 100, 'status' => 'restricted'],
            ['shop_id' => 3, 'total_sales' => 7300, 'due_commission' => 0, 'credit_limit' => 100, 'status' => 'active'],
            ['shop_id' => 4, 'total_sales' => 1600, 'due_commission' => 32, 'credit_limit' => 100, 'status' => 'active'],
            ['shop_id' => 5, 'total_sales' => 0, 'due_commission' => 0, 'credit_limit' => 100, 'status' => 'active'],
            ['shop_id' => 6, 'total_sales' => 0, 'due_commission' => 0, 'credit_limit' => 100, 'status' => 'active'],
            ['shop_id' => 7, 'total_sales' => 0, 'due_commission' => 0, 'credit_limit' => 100, 'status' => 'active'],
            ['shop_id' => 8, 'total_sales' => 0, 'due_commission' => 0, 'credit_limit' => 100, 'status' => 'active'],
            ['shop_id' => 9, 'total_sales' => 0, 'due_commission' => 0, 'credit_limit' => 100, 'status' => 'active'],
            ['shop_id' => 10, 'total_sales' => 0, 'due_commission' => 0, 'credit_limit' => 100, 'status' => 'active'],
        ];

        foreach ($wallets as $wallet) {
            DB::table('wallets')->updateOrInsert(['shop_id' => $wallet['shop_id']], array_merge($wallet, ['created_at' => now(), 'updated_at' => now()]));
        }
    }
}
